spring:
  application:
    name: zuul-service
 
#Tomcat Embedded Server Configuration
server:
  port: 7000
 
#Zuul Configuration Properties
zuul:
  routes:
      serv-greet:
        path: /servicio-basico/**
        serviceId: basico-microservicio
 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
